Feature: Validation test interviews
  In order to ensure that the application behaves correctly, I want to run
  through some different scenarios.

  Scenario: Neressia Arrington
    Given I start the interview "docassemble.MAEvictionDefense:data/questions/eviction.yml"
    Then I should see the phrase "Massachusetts Eviction Defense"
    And I click the button "Continue"
    Then I should see the phrase "This site does not give legal advice."
    And I click the button "I do not understand"
    Then I should see the phrase "Sorry, you cannot proceed with the interview."
    And I click the back button
    Then I should see the phrase "This site does not give legal advice."
    And I click the button "I’m not sure"
    Then I should see the phrase "Sorry, you cannot proceed with the interview."
    And I click the button "Restart"
    Then I should see the phrase "Massachusetts Eviction Defense"
    And I click the button "Continue"
    Then I should see the phrase "This site does not give legal advice."
    And I click the button "I understand"
    Then I should see the phrase "Who is completing this interview?"
    And I click the button "Tenant or helper"
    Then I should see the phrase "Overview of Tenant’s Rights in Evictions in Massachusetts"
    And I click the button "Continue"
    Then I should see the phrase "Getting Started"
    And I click the button "Continue"
    Then I should see the phrase "What is your name?"
    And I set "First Name" to "Neressia"
    And I set "Last Name" to "Arrington"
    And I click the button "Continue"
    Then I should see the phrase "Upcoming court dates"
    And I click the button "Continue"
    Then I should see the phrase "Your right to a jury trial"
    And I click the button "Claim a jury trial"
    Then I should see the phrase "What is your current address?"
    And I set "address" to "519 Harrison Avenue"
    And I set "city" to "Boston"
    And I select "Massachusetts" as the "state"
    And I set "zip" to "02118"
    And I set "county" to "Suffolk County"
    And I click the button "Continue"
    Then I should see the phrase "Information about Neressia Arrington"
    And I click the option "I or someone who lives with me has a disability"
    And I click the option "My rent is subsidized."
    And I click the button "Continue"
    Then I should see the phrase "What is the Landlord’s name?"
    And I set "Name" to "Maloney Properties Inc. Managing Agent"
    Then I should see the phrase "Information about 519 Harrison Avenue"
    And I wait forever
